version: '3.8'

services:
  bella-ai-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bella_ai_platform_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
