/**
 * BELLA EOS — Creative Planning Engine
 * creative-planning-engine.ts
 *
 * The pipeline engine that transforms a raw Creative Request
 * into a fully-structured CreativePlan.
 *
 * Pipeline stages (each is a private method):
 *   1. analyzeIntent()       ← campaign type, KPI, audience label
 *   2. mapBrandIntelligence() ← palette, luxury level, tone
 *   3. selectStyle()         ← picks StyleGraph from STYLE_LIBRARY
 *   4. planScene()           ← environment, subjects, props
 *   5. planComposition()     ← copy space %, subject placement, rule
 *   6. planLighting()        ← ambient, key, rim, mood
 *   7. planCamera()          ← body, lens, angle, dof, quality
 *   8. optimizeForImagen()   ← natural commercial-language prompt (~480 chars)
 *   9. optimizeForFlux()     ← tag-dense comma-separated keywords
 *  10. optimizeForDalle()    ← full descriptive sentence + avoidance clause
 *  11. buildNegativePrompt() ← merged negative from style + universal base
 *
 * Output: CreativePlan — a portable structured object.
 * PosterDesignSkill, VideoWorker, SlideWorker, etc. consume this object.
 */

import type { BrandDnaContext, CreativePlan, CompositionSpec } from './creative-plan';
import { STYLE_LIBRARY } from './style-library';
import { getDefaultKernel } from './kernel/kernel-factory';
import { CreativeKernel } from './kernel/creative-kernel';

// ── Creative Request ──────────────────────────────────────────────────────────
export interface CreativeRequest {
  objective:          string;
  copywriterSnippet?: string;
  brandDna?:          BrandDnaContext;
  format?:            '16:9' | '1:1' | '9:16' | '4:3';
  medium?:            'image' | 'video' | 'slide' | 'landing_page' | '3d';
  preferredModel?:    string;
}

// ── Universal Negative Prompt ─────────────────────────────────────────────────
const UNIVERSAL_NEGATIVE =
  'text, words, letters, typography, font, written language, ' +
  'logo, brand name, watermark, signature, stamp, label, ' +
  'deformed anatomy, extra limbs, duplicate objects, ' +
  'motion blur, camera shake, out-of-focus foreground, ' +
  'low quality, pixelated, jpeg artifact, noise, grain, ' +
  'bad composition, tilted horizon, cropped poorly';

// ── Engine ────────────────────────────────────────────────────────────────────
export class CreativePlanningEngine {

  /**
   * Asynchronous entry point calling the new v5 Creative Runtime Kernel.
   * Prompts are generated by model-specific adapters.
   */
  static async planAsync(request: CreativeRequest): Promise<CreativePlan> {
    const kernel = getDefaultKernel();
    const state = await kernel.run(request);
    return CreativeKernel.extractPlan(state);
  }

  /**
   * Main entry point.
   * Runs all pipeline stages and returns a fully-populated CreativePlan.
   */
  static plan(request: CreativeRequest): CreativePlan {
    const {
      objective,
      copywriterSnippet = '',
      brandDna,
      format = '16:9',
      medium = 'image',
    } = request;

    const lo = objective.toLowerCase();

    // ── Stage 1: Intent Analysis ─────────────────────────────────────────────
    const { campaignType, intent, tone, targetKPI, audienceLabel } =
      CreativePlanningEngine.analyzeIntent(lo, objective, brandDna, copywriterSnippet);

    // ── Stage 2: Brand Intelligence ──────────────────────────────────────────
    const { brandName, palette, luxuryLevel } =
      CreativePlanningEngine.mapBrandIntelligence(brandDna, campaignType);

    // ── Stage 3: Style Selection ─────────────────────────────────────────────
    const styleGraph = CreativePlanningEngine.selectStyle(lo, brandDna, luxuryLevel);

    // ── Stage 4: Scene Planning ──────────────────────────────────────────────
    const { environment, subjects, props } =
      CreativePlanningEngine.planScene(lo, campaignType, styleGraph.id, subjects_from_brand(brandDna));

    // ── Stage 5: Composition ─────────────────────────────────────────────────
    const composition = CreativePlanningEngine.planComposition(campaignType, styleGraph.id);

    // ── Stage 6: Lighting ────────────────────────────────────────────────────
    const lighting = styleGraph.lighting;

    // ── Stage 7: Camera ──────────────────────────────────────────────────────
    const camera = {
      body:    styleGraph.camera.body,
      lens:    styleGraph.camera.lens,
      angle:   styleGraph.camera.angle,
      dof:     styleGraph.depth,
      quality: styleGraph.camera.quality,
    };

    // ── Stage 8–10: Model Optimizers ─────────────────────────────────────────
    const contextSeed = {
      environment,
      subjects,
      composition,
      lighting,
      camera,
      styleGraph,
      palette,
      brandName,
      tone,
    };

    const imagenPrompt  = CreativePlanningEngine.optimizeForImagen(contextSeed);
    const fluxPrompt    = CreativePlanningEngine.optimizeForFlux(contextSeed);
    const dallePrompt   = CreativePlanningEngine.optimizeForDalle(contextSeed);

    // ── Stage 11: Negative Prompt ────────────────────────────────────────────
    const negativePrompt = CreativePlanningEngine.buildNegativePrompt(styleGraph.negativeBase);

    return {
      objective,
      campaignType,
      medium,
      format,
      intent,
      tone,
      targetKPI,
      audienceLabel,
      brandName,
      palette,
      styleId:     styleGraph.id,
      styleGraph,
      luxuryLevel,
      environment,
      subjects,
      props,
      composition,
      lighting,
      camera,
      imagenPrompt,
      fluxPrompt,
      dallePrompt,
      negativePrompt,
      decisionTrace: [],
      generatedAt: new Date().toISOString(),
      runtimeVersion: '2.0.0',
    };
  }

  // ── STAGE 1: Intent Analysis ──────────────────────────────────────────────
  private static analyzeIntent(
    lo: string,
    objective: string,
    brandDna?: BrandDnaContext,
    copywriterSnippet?: string
  ) {
    let campaignType: CreativePlan['campaignType'] = 'generic';
    let intent     = `Create a compelling commercial visual for: ${objective}`;
    let tone       = brandDna?.voiceTone || 'professional, premium, trustworthy';
    let targetKPI  = 'brand awareness and CTA engagement';
    let audienceLabel = brandDna?.targetSegment || 'Business decision-makers';

    if (lo.includes('spa') || lo.includes('thẩm mỹ') || lo.includes('làm đẹp') || lo.includes('salon') || lo.includes('wellness')) {
      campaignType  = 'sales';
      intent        = 'Attract high-end spa and beauty business owners to adopt AI management software';
      tone          = brandDna?.voiceTone || 'luxury, serene, authoritative, trustworthy';
      targetKPI     = 'demo booking conversion rate';
      audienceLabel = brandDna?.targetSegment || 'Premium Spa Owners & Beauty Studio Managers';
    } else if (lo.includes('bất động sản') || lo.includes('căn hộ') || lo.includes('chung cư') || lo.includes('nhà đất')) {
      campaignType  = 'product';
      intent        = 'Drive qualified leads to explore premium residential real estate investment';
      tone          = brandDna?.voiceTone || 'aspirational, trustworthy, elegant, modern';
      targetKPI     = 'lead inquiry form submission';
      audienceLabel = brandDna?.targetSegment || 'High-net-worth property investors and home buyers';
    } else if (lo.includes('thời trang') || lo.includes('quần áo') || lo.includes('boutique') || lo.includes('fashion')) {
      campaignType  = 'brand';
      intent        = 'Build premium fashion brand awareness and drive first purchase conversion';
      tone          = brandDna?.voiceTone || 'bold, stylish, editorial, confident';
      targetKPI     = 'e-commerce click-through rate';
      audienceLabel = brandDna?.targetSegment || 'Fashion-forward urban consumers';
    } else if (lo.includes('tuyển dụng') || lo.includes('recruitment') || lo.includes('hr') || lo.includes('nhân sự')) {
      campaignType  = 'recruitment';
      intent        = 'Attract high-quality candidates to open positions with a strong employer brand impression';
      tone          = brandDna?.voiceTone || 'confident, welcoming, innovative, progressive';
      targetKPI     = 'job application click-through rate';
      audienceLabel = brandDna?.targetSegment || 'Experienced professionals and top graduates';
    } else if (lo.includes('công nghệ') || lo.includes('ai') || lo.includes('software') || lo.includes('digital') || lo.includes('platform')) {
      campaignType  = 'product';
      intent        = 'Drive enterprise decision-makers to explore an AI-powered business platform';
      tone          = brandDna?.voiceTone || 'innovative, intelligent, futuristic, authoritative';
      targetKPI     = 'demo or free trial sign-up rate';
      audienceLabel = brandDna?.targetSegment || 'CTO, CEO, Operations Directors at mid-to-large enterprises';
    } else if (lo.includes('event') || lo.includes('sự kiện') || lo.includes('hội thảo') || lo.includes('workshop')) {
      campaignType  = 'event';
      intent        = 'Drive event registrations with high urgency and clear value proposition';
      tone          = brandDna?.voiceTone || 'energetic, urgent, exciting, professional';
      targetKPI     = 'event registration conversion rate';
      audienceLabel = brandDna?.targetSegment || 'Professional community and industry peers';
    }

    return { campaignType, intent, tone, targetKPI, audienceLabel };
  }

  // ── STAGE 2: Brand Intelligence ──────────────────────────────────────────
  private static mapBrandIntelligence(
    brandDna?: BrandDnaContext,
    campaignType?: CreativePlan['campaignType']
  ) {
    const brandName = brandDna?.brandName || 'BELLA EOS';

    // Resolve luxury level from visual style keywords + campaign type
    let luxuryLevel: 1 | 2 | 3 | 4 | 5 = 3;
    const vs = (brandDna?.visualStyle || '').toLowerCase();
    if (vs.includes('luxury') || vs.includes('ultra') || vs.includes('premium') || vs.includes('sang trọng')) luxuryLevel = 5;
    else if (vs.includes('high-end') || vs.includes('elegant')) luxuryLevel = 4;
    else if (vs.includes('minimal') || vs.includes('corporate') || vs.includes('clean')) luxuryLevel = 2;
    else if (vs.includes('flat') || vs.includes('simple')) luxuryLevel = 1;
    else if (campaignType === 'sales' || campaignType === 'brand') luxuryLevel = 4;
    else if (campaignType === 'recruitment' || campaignType === 'event') luxuryLevel = 2;

    const palette = {
      primary:   brandDna?.brandColors?.primary  || '#061E17',
      accent:    brandDna?.brandColors?.accent    || '#D4AF37',
      neutral:   brandDna?.brandColors?.neutral   || '#F5F5F0',
      surface:   '#0D0D0D',   // resolved from style in later stage
    };

    return { brandName, palette, luxuryLevel };
  }

  // ── STAGE 3: Style Selection ─────────────────────────────────────────────
  private static selectStyle(
    lo: string,
    brandDna?: BrandDnaContext,
    luxuryLevel?: number
  ) {
    const vs = (brandDna?.visualStyle || '').toLowerCase();

    if (lo.includes('cyberpunk') || lo.includes('future') || vs.includes('cyberpunk') || vs.includes('hi-tech') || lo.includes('hologram')) {
      return STYLE_LIBRARY.cyberpunk;
    }
    if (lo.includes('bento') || vs.includes('bento') || vs.includes('3d') || lo.includes('dashboard') || lo.includes('giao diện')) {
      return STYLE_LIBRARY.bento;
    }
    if (lo.includes('thời trang') || lo.includes('fashion') || lo.includes('boutique') || vs.includes('fashion') || vs.includes('editorial')) {
      return STYLE_LIBRARY.fashion;
    }
    if (lo.includes('tuyển dụng') || lo.includes('recruitment') || lo.includes('b2b') || vs.includes('corporate')) {
      return STYLE_LIBRARY.corporate;
    }
    if (lo.includes('nature') || lo.includes('organic') || lo.includes('wellness') || vs.includes('natural') || vs.includes('green')) {
      return STYLE_LIBRARY.nature;
    }
    if ((luxuryLevel && luxuryLevel >= 4) || lo.includes('spa') || lo.includes('thẩm mỹ') || lo.includes('làm đẹp') || vs.includes('luxury') || vs.includes('sang trọng')) {
      return STYLE_LIBRARY.luxury;
    }
    if (vs.includes('minimal') || vs.includes('clean') || vs.includes('apple') || lo.includes('minimalist')) {
      return STYLE_LIBRARY.minimalist;
    }

    // Fallback: choose by luxury level
    if ((luxuryLevel ?? 3) >= 4) return STYLE_LIBRARY.luxury;
    if ((luxuryLevel ?? 3) <= 2) return STYLE_LIBRARY.minimalist;
    return STYLE_LIBRARY.corporate;
  }

  // ── STAGE 4: Scene Planning ──────────────────────────────────────────────
  private static planScene(
    lo: string,
    campaignType: CreativePlan['campaignType'],
    styleId: string,
    brandSubjects: string[]
  ): { environment: string; subjects: string[]; props: string[] } {
    const baseEnv = STYLE_LIBRARY[styleId]?.environment ?? 'a clean premium commercial background';

    let subjects: string[] = [...brandSubjects];
    let props:    string[] = [];
    let environment = baseEnv;

    if (lo.includes('spa') || lo.includes('thẩm mỹ') || lo.includes('làm đẹp') || lo.includes('salon')) {
      subjects = ['premium glass cosmetic jars on polished marble surface', 'soft white rolled towels', 'delicate orchid flower arrangement'];
      props    = ['scented candle with soft flame', 'bamboo wooden accent tray', 'smooth river pebbles'];
      environment = 'modern luxury spa wellness treatment room with floor-to-ceiling frosted glass, warm ambient lighting, natural stone accent wall';
    } else if (lo.includes('bất động sản') || lo.includes('căn hộ') || lo.includes('chung cư')) {
      subjects = ['luxury modern architectural villa at golden hour', 'stunning glass curtain wall facade', 'glowing warm interior lights'];
      props    = ['reflection pool with still water', 'manicured tropical garden', 'panoramic sunset sky'];
      environment = 'premium residential exterior with breathtaking architectural design, golden hour sunset backdrop, immaculate landscaping';
    } else if (lo.includes('thời trang') || lo.includes('boutique') || lo.includes('fashion')) {
      subjects = ['premium designer garments on minimalist chrome display rack', 'luxury accessories flat-lay on marble surface'];
      props    = ['professional studio light reflection on floor', 'simple linen accent prop'];
      environment = 'exclusive luxury fashion boutique interior with high-gloss terrazzo floor and minimalist chrome fixtures';
    } else if (lo.includes('công nghệ') || lo.includes('ai') || lo.includes('software') || lo.includes('platform')) {
      subjects = ['abstract 3D AI neural network data sphere', 'floating holographic interface panels', 'glowing digital data streams'];
      props    = ['isometric server rack illustration', 'subtle circuit board texture overlay'];
      environment = 'futuristic AI research facility with glowing holographic interfaces and dark atmospheric ambience';
    } else if (lo.includes('tuyển dụng') || lo.includes('recruitment')) {
      subjects = ['modern executive conference room table in soft focus', 'clean corporate interior architectural elements'];
      props    = ['soft daylight from floor-to-ceiling windows', 'city skyline background through glass'];
      environment = 'professional modern corporate headquarters interior with city panorama';
    } else {
      subjects = ['premium product showcase with clean surfaces', 'brand accent element'];
      props    = ['subtle lighting gradient', 'minimal geometric form'];
    }

    return { environment, subjects, props };
  }

  // ── STAGE 5: Composition Planning ────────────────────────────────────────
  private static planComposition(
    campaignType: CreativePlan['campaignType'],
    styleId: string
  ): CompositionSpec {
    if (styleId === 'cyberpunk' || styleId === 'bento') {
      return {
        copySpacePercent:  55,
        subjectPlacement:  'right',
        rule:              'rule_of_thirds',
        perspective:       'dynamic high angle, 20-degree tilt, wide-angle composition',
        leadingLines:      'neon grid lines and circuit traces guiding eye from left to subject on right',
      };
    }
    if (campaignType === 'brand' || styleId === 'fashion') {
      return {
        copySpacePercent:  50,
        subjectPlacement:  'right',
        rule:              'golden_ratio',
        perspective:       'editorial eye-level, slight downward tilt for authority',
        leadingLines:      'rack geometry and floor reflection lines drawing eye toward subject',
      };
    }
    if (campaignType === 'recruitment' || styleId === 'corporate') {
      return {
        copySpacePercent:  60,
        subjectPlacement:  'right',
        rule:              'rule_of_thirds',
        perspective:       'perfectly level professional eye-level',
        leadingLines:      'architectural window frames creating strong vertical leading lines',
      };
    }
    // Default: sales / luxury / nature
    return {
      copySpacePercent:  62,
      subjectPlacement:  'right',
      rule:              'rule_of_thirds',
      perspective:       'slight 5-degree upward tilt, intimate and aspirational',
      leadingLines:      'stone surface edge and natural light gradient guiding eye from left toward right subject area',
    };
  }

  // ── STAGE 8: Imagen Optimizer ────────────────────────────────────────────
  /** Imagen responds best to natural, commercial photographic language.
   *  Max ~480 chars. No Vietnamese. No marketing copy words. */
  private static optimizeForImagen(ctx: PromptContext): string {
    const comp = `${ctx.composition.copySpacePercent}% of the left canvas is left completely empty and clean as negative space for text overlay, subject is ${ctx.composition.subjectPlacement}-aligned using ${ctx.composition.rule.replace(/_/g, ' ')}`;
    const parts = [
      `Commercial design background depicting ${ctx.subjects[0]}`,
      ctx.environment,
      ctx.styleGraph.material,
      comp,
      ctx.lighting.ambient,
      ctx.lighting.key,
      ctx.lighting.mood,
      ctx.camera.body,
      ctx.camera.lens,
      ctx.styleGraph.depth,
      ctx.styleGraph.postProcess,
    ];
    return parts.filter(Boolean).join('. ').replace(/\.\./g, '.').substring(0, 1800);
  }

  // ── STAGE 9: Flux Optimizer ──────────────────────────────────────────────
  /** Flux (SDXL-based) responds best to comma-separated tag-dense prompts. */
  private static optimizeForFlux(ctx: PromptContext): string {
    const tags = [
      ctx.subjects[0],
      ctx.environment,
      ctx.styleGraph.id + ' style',
      ctx.styleGraph.material,
      ctx.lighting.mood,
      ctx.camera.body,
      ctx.camera.lens,
      `f/${ctx.camera.lens?.match(/f\/([\d.]+)/)?.[1] ?? '2.8'}`,
      ctx.styleGraph.postProcess,
      ctx.styleGraph.depth,
      `${ctx.composition.copySpacePercent}% left side empty clean background`,
      'commercial photography',
      'ultra detailed',
      '8K',
      'photorealistic',
      'no text',
      'no letters',
    ];
    return tags.filter(Boolean).join(', ');
  }

  // ── STAGE 10: DALL-E Optimizer ───────────────────────────────────────────
  /** DALL-E 3 responds best to a clear descriptive paragraph followed by explicit avoidance. */
  private static optimizeForDalle(ctx: PromptContext): string {
    const base = `A high-quality commercial photographic background image for a marketing banner. ${ctx.subjects[0]}. Setting: ${ctx.environment}. The left ${ctx.composition.copySpacePercent}% of the image is left deliberately empty with a clean, minimal surface area — this space is reserved for marketing copy text overlay. The visual subject is positioned on the ${ctx.composition.subjectPlacement} side. Lighting: ${ctx.lighting.ambient}, ${ctx.lighting.key}. ${ctx.styleGraph.material}. ${ctx.styleGraph.postProcess}. Photographed on ${ctx.camera.body} with ${ctx.camera.lens}.`;
    const avoidance = `Do not include any text, words, letters, numbers, writing, labels, watermarks, logos, or typographic elements anywhere in the image.`;
    return `${base} ${avoidance}`;
  }

  // ── STAGE 11: Negative Prompt Builder ────────────────────────────────────
  private static buildNegativePrompt(styleNegative: string): string {
    const terms = new Set([
      ...UNIVERSAL_NEGATIVE.split(', '),
      ...styleNegative.split(', '),
    ]);
    return Array.from(terms).join(', ');
  }
}

// ── Internal type ────────────────────────────────────────────────────────────
interface PromptContext {
  environment:  string;
  subjects:     string[];
  composition:  CompositionSpec;
  lighting:     CreativePlan['lighting'];
  camera:       CreativePlan['camera'];
  styleGraph:   import('./creative-plan').StyleGraph;
  palette:      CreativePlan['palette'];
  brandName:    string;
  tone:         string;
}

// ── Helper ────────────────────────────────────────────────────────────────────
function subjects_from_brand(brandDna?: BrandDnaContext): string[] {
  if (!brandDna?.brandName) return [];
  return [];  // reserved for brand-specific subjects (e.g. product hero shot)
}
