/**
 * verify-kernel-v5.ts
 * Verification script for the new v5 Creative Runtime Kernel, Planners, and DAG waves.
 * Run: npx tsx scratch/verify-kernel-v5.ts
 */

import { getDefaultKernel } from '../src/core/creative/kernel/kernel-factory';
import { CreativeKernel } from '../src/core/creative/kernel/creative-kernel';
import { KernelEventBus, KernelEvent } from '../src/core/creative/kernel/kernel-event-bus';
import { createDefaultKernel } from '../src/core/creative/kernel/kernel-factory';

const RESET  = '\x1b[0m';
const GREEN  = '\x1b[32m';
const RED    = '\x1b[31m';
const CYAN   = '\x1b[36m';
const YELLOW = '\x1b[33m';

let passed = 0;
let failed = 0;

function assert(label: string, condition: boolean, info?: string) {
  if (condition) {
    console.log(`  ${GREEN}✓${RESET} ${label}`);
    passed++;
  } else {
    console.log(`  ${RED}✗ FAIL${RESET} ${label}${info ? ` → ${info}` : ''}`);
    failed++;
  }
}

async function run() {
  console.log(`\n${CYAN}═══════════════════════════════════════════════════════${RESET}`);
  console.log(`${CYAN} BELLA EOS — Creative Runtime Kernel v5 Verification${RESET}`);
  console.log(`${CYAN}═══════════════════════════════════════════════════════${RESET}\n`);

  // 1. Capture events to verify event bus logging
  const events: KernelEvent[] = [];
  const bus = new KernelEventBus().on('*', (e) => {
    events.push(e);
  });

  const kernel = createDefaultKernel(bus);

  const request = {
    objective: 'Thiết kế banner cho dịch vụ spa cao cấp sang trọng',
    copywriterSnippet: 'Đánh thức vẻ đẹp tự nhiên của bạn',
    brandDna: {
      brandName: 'BELLA SPA',
      voiceTone: 'nhẹ nhàng, quý phái',
      visualStyle: 'Luxury Wellness',
      luxuryLevel: 5,
    },
    format: '16:9' as const,
    medium: 'image' as const,
  };

  console.log(`${YELLOW}▶ Running async planning process...${RESET}`);
  const state = await kernel.run(request);
  const plan = CreativeKernel.extractPlan(state);

  console.log(`\n${YELLOW}▶ Verifying Output Plan Structure & Values:${RESET}`);
  assert('plan.objective matches', plan.objective === request.objective);
  assert('plan.styleId is luxury', plan.styleId === 'luxury');
  assert('plan.luxuryLevel is 5', plan.luxuryLevel === 5);
  assert('plan.palette has colors', !!plan.palette.primary && !!plan.palette.accent);
  assert('plan.scene environment is set', !!plan.scene?.environment.includes('spa'));
  assert('plan.camera lens choice is set', !!(plan.camera.lens === '85mm f/1.4 GM' || plan.camera.lens?.includes('90mm') || plan.camera.lens?.includes('100mm')));
  assert('plan.lighting keylight is set', !!(plan.lighting.keyLight?.includes('soft') || plan.lighting.keyLight?.includes('Soft')));
  assert('plan.composition copy space is set', (plan.composition.copySpacePercent ?? 0) >= 50);

  // Model-specific prompts
  assert('imagenPrompt is generated by adapter', plan.imagenPrompt.length > 50 && plan.imagenPrompt.toLowerCase().includes('luxury'));
  assert('fluxPrompt is generated by adapter', plan.fluxPrompt.length > 50 && plan.fluxPrompt.includes('commercial photography'));
  assert('dallePrompt is generated by adapter', plan.dallePrompt.length > 80 && plan.dallePrompt.toLowerCase().includes('do not include'));

  // Quality gate
  assert('qualityScore exists', !!plan.qualityScore);
  assert('qualityScore verdict is pass or warn', plan.qualityScore?.verdict === 'pass' || plan.qualityScore?.verdict === 'warn');
  assert('qualityScore overall is set', (plan.qualityScore?.overall ?? 0) >= 60);

  // Decision trace
  assert('decisionTrace exists', plan.decisionTrace.length >= 8);
  console.log(`\n  ${CYAN}Decision Trace History:${RESET}`);
  for (const entry of plan.decisionTrace) {
    console.log(`    - [${entry.planner}] ${entry.decision} (${entry.reason})`);
  }

  // Event bus count
  console.log(`\n${YELLOW}▶ Verifying Event Bus Lifecycle:${RESET}`);
  assert('kernel:started event captured', events.some(e => e.type === 'kernel:started'));
  assert('wave:started events captured', events.filter(e => e.type === 'wave:started').length >= 4);
  assert('planner:after events captured', events.filter(e => e.type === 'planner:after').length >= 8);
  assert('quality event captured', events.some(e => e.type.startsWith('quality:')));
  assert('kernel:completed event captured', events.some(e => e.type === 'kernel:completed'));

  console.log(`\n${CYAN}═══════════════════════════════════════════════════════${RESET}`);
  const total = passed + failed;
  if (failed === 0) {
    console.log(`${GREEN}   ALL ${total} KERNEL ASSERTIONS PASSED SUCCESSFULLY${RESET}`);
  } else {
    console.log(`${RED}   ${failed} / ${total} KERNEL ASSERTIONS FAILED${RESET}`);
    process.exit(1);
  }
  console.log(`${CYAN}═══════════════════════════════════════════════════════${RESET}\n`);
}

run().catch((e) => {
  console.error('Unhandled verification error:', e);
  process.exit(1);
});
